Wed, 31 Oct 2018 13:12:52 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Wed, 31 Oct 2018 13:12:52 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Wed, 31 Oct 2018 13:12:52 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Wed, 31 Oct 2018 13:12:52 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Wed, 31 Oct 2018 13:12:52 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Wed, 31 Oct 2018 13:12:52 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Wed, 31 Oct 2018 13:12:52 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Wed, 31 Oct 2018 13:12:52 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Wed, 31 Oct 2018 13:12:52 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Wed, 31 Oct 2018 13:12:52 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Wed, 31 Oct 2018 13:12:52 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Wed, 31 Oct 2018 13:16:25 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/business/ci/ci_task_queue_service.py", line 39, in start_user
    started_by = User.objects.get(id=ci_task_history.StartedBy)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 10:14:28 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/business/auth_user/user_service.py", line 29, in get_user
    user=User.objects.get(id=userid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 10:14:28 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:14:28 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:14:28 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:14:28 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:14:28 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:14:28 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:14:28 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:14:28 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:14:28 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:14:28 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:14:28 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:15:17 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/business/auth_user/user_service.py", line 29, in get_user
    user=User.objects.get(id=userid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 10:15:17 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:15:17 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:15:17 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:15:17 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:15:17 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:15:17 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:15:17 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:15:17 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:15:17 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:15:17 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:15:17 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:16:21 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/business/auth_user/user_service.py", line 29, in get_user
    user=User.objects.get(id=userid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 10:16:22 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:16:22 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:16:22 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:16:22 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:16:22 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:16:22 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:16:22 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:16:22 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:16:22 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:16:22 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:16:22 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:16:36 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/business/auth_user/user_service.py", line 29, in get_user
    user=User.objects.get(id=userid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 10:20:35 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/business/auth_user/user_service.py", line 29, in get_user
    user=User.objects.get(id=userid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 10:21:20 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/business/auth_user/user_service.py", line 29, in get_user
    user=User.objects.get(id=userid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 10:29:00 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/business/auth_user/user_service.py", line 29, in get_user
    user=User.objects.get(id=userid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 10:29:21 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/business/auth_user/user_service.py", line 29, in get_user
    user=User.objects.get(id=userid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 10:29:21 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:29:21 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:29:21 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:29:21 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:29:21 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:29:21 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:29:21 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:29:21 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:29:21 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:29:21 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:29:21 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:14 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/business/auth_user/user_service.py", line 29, in get_user
    user=User.objects.get(id=userid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 10:44:14 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:14 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:14 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:14 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:14 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:14 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:14 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:14 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:14 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:14 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:14 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:19 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/business/auth_user/user_service.py", line 29, in get_user
    user=User.objects.get(id=userid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 10:44:19 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:19 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:19 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:19 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:19 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:19 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:19 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:19 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:19 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:19 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:19 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:23 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/business/auth_user/user_service.py", line 29, in get_user
    user=User.objects.get(id=userid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 10:44:23 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:23 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:23 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:23 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:23 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:23 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:23 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:23 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:23 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:23 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:44:23 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 10:54:41 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/business/ci/ci_task_queue_service.py", line 39, in start_user
    started_by = User.objects.get(id=ci_task_history.StartedBy)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 10:54:42 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/business/ci/ci_task_queue_service.py", line 39, in start_user
    started_by = User.objects.get(id=ci_task_history.StartedBy)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 10:55:31 simplelogger.py[line:28] ERROR list index out of range
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/business/ci/ci_task_queue_service.py", line 38, in start_user
    ci_task_history = CITaskHistory.objects.get_history_by_tq(tq_id)
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/ci_model_manager.py", line 187, in get_history_by_tq
    return result[0]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 307, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
Thu, 01 Nov 2018 10:55:31 simplelogger.py[line:28] ERROR list index out of range
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/business/ci/ci_task_queue_service.py", line 38, in start_user
    ci_task_history = CITaskHistory.objects.get_history_by_tq(tq_id)
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/model_managers/ci_model_manager.py", line 187, in get_history_by_tq
    return result[0]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 307, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
Thu, 01 Nov 2018 11:53:43 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/business/ci/ci_task_queue_service.py", line 39, in start_user
    started_by = User.objects.get(id=ci_task_history.StartedBy)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 11:53:43 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/business/ci/ci_task_queue_service.py", line 39, in start_user
    started_by = User.objects.get(id=ci_task_history.StartedBy)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 12:03:33 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/business/ci/ci_task_queue_service.py", line 39, in start_user
    started_by = User.objects.get(id=ci_task_history.StartedBy)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 12:03:33 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/business/ci/ci_task_queue_service.py", line 39, in start_user
    started_by = User.objects.get(id=ci_task_history.StartedBy)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 12:52:42 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/business/ci/ci_task_queue_service.py", line 39, in start_user
    started_by = User.objects.get(id=ci_task_history.StartedBy)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 12:52:42 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/business/ci/ci_task_queue_service.py", line 39, in start_user
    started_by = User.objects.get(id=ci_task_history.StartedBy)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 13:51:43 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/business/ci/ci_task_queue_service.py", line 39, in start_user
    started_by = User.objects.get(id=ci_task_history.StartedBy)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 13:51:43 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/coding.net/doraemon_nirvana_lte/doraemon/business/ci/ci_task_queue_service.py", line 39, in start_user
    started_by = User.objects.get(id=ci_task_history.StartedBy)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 14:27:48 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:27:48 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:27:48 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:27:48 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:27:48 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:27:48 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:27:48 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:27:48 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:27:48 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:27:48 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:27:48 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:27:48 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/doraemon/auth_extend/user/viewmodels/vm_action_log.py", line 64, in user_avatar
    action_user=User.objects.get(id=self.action_log.User)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 14:27:48 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/doraemon/auth_extend/user/viewmodels/vm_action_log.py", line 34, in user_name
    action_user=User.objects.get(id=self.action_log.User)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 14:27:56 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:27:56 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:27:56 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:27:56 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:27:56 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:27:56 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:27:56 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:27:56 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:27:56 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:27:56 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:27:56 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:27:56 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/doraemon/auth_extend/user/viewmodels/vm_action_log.py", line 64, in user_avatar
    action_user=User.objects.get(id=self.action_log.User)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 14:27:56 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/doraemon/auth_extend/user/viewmodels/vm_action_log.py", line 34, in user_name
    action_user=User.objects.get(id=self.action_log.User)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 14:28:03 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:28:03 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:28:03 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:28:03 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:28:03 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:28:03 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:28:03 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:28:03 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:28:03 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:28:03 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:28:03 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:28:03 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/doraemon/auth_extend/user/viewmodels/vm_action_log.py", line 64, in user_avatar
    action_user=User.objects.get(id=self.action_log.User)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 14:28:03 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/doraemon/auth_extend/user/viewmodels/vm_action_log.py", line 34, in user_name
    action_user=User.objects.get(id=self.action_log.User)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 14:38:05 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/business/auth_user/user_service.py", line 29, in get_user
    user=User.objects.get(id=userid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 14:38:05 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:05 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:05 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:05 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:05 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:05 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:05 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:05 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:05 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:05 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:05 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:14 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/business/auth_user/user_service.py", line 29, in get_user
    user=User.objects.get(id=userid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 14:38:14 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:15 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:15 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:15 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:15 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:15 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:15 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:15 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:15 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:15 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:15 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:34 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/business/auth_user/user_service.py", line 29, in get_user
    user=User.objects.get(id=userid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 14:38:34 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:34 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:34 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:34 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:34 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:34 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:34 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:34 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:34 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:34 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:38:34 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:41:01 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/business/auth_user/user_service.py", line 29, in get_user
    user=User.objects.get(id=userid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 14:41:02 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:41:02 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:41:02 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:41:02 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:41:02 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:41:02 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:41:02 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:41:02 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:41:02 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:41:02 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:41:02 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:49:43 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:49:43 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:49:43 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:49:43 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:49:43 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:49:43 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:49:43 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:49:43 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:49:43 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:49:43 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:49:43 simplelogger.py[line:28] ERROR Project matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/project_model_manager.py", line 198, in get
    result=super(ProjectManager,self).get_queryset().get(id=projectid)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
doraemon.project.models.DoesNotExist: Project matching query does not exist.
Thu, 01 Nov 2018 14:49:43 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/doraemon/auth_extend/user/viewmodels/vm_action_log.py", line 64, in user_avatar
    action_user=User.objects.get(id=self.action_log.User)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 14:49:43 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/doraemon/auth_extend/user/viewmodels/vm_action_log.py", line 34, in user_name
    action_user=User.objects.get(id=self.action_log.User)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 14:50:01 simplelogger.py[line:28] ERROR Unsupported lookup 'exclude' for IntegerField or join on the field not permitted.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/business/ci/ci_task_service.py", line 50, in get_ci_tasks_recently_build
    result=CITaskService.get_product_ci_tasks(request, task_type, product_id).filter(LastHistory__exclude=(0,))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 836, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 854, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1252, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    split_subq=split_subq,
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1214, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1078, in build_lookup
    lhs = self.try_transform(lhs, lookups[-1])
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/sql/query.py", line 1114, in try_transform
    (name, lhs.output_field.__class__.__name__))
django.core.exceptions.FieldError: Unsupported lookup 'exclude' for IntegerField or join on the field not permitted.
Thu, 01 Nov 2018 14:50:01 simplelogger.py[line:28] ERROR eval() arg 1 must be a string, bytes or code object
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/doraemon/ci/views/ci_task_view.py", line 165, in more_dashboard_task_list
    result=page_worker.dashboard_more_task_list(request)
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/doraemon/ci/pagefactory/ci_task_pageworker.py", line 103, in dashboard_more_task_list
    dm_ci_tasks = CITaskService.filter_tasks(request)
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/business/ci/ci_task_service.py", line 118, in filter_tasks
    result=[task for task in result if task.Project in eval(project_ids)]
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/business/ci/ci_task_service.py", line 118, in <listcomp>
    result=[task for task in result if task.Project in eval(project_ids)]
TypeError: eval() arg 1 must be a string, bytes or code object
Thu, 01 Nov 2018 14:50:16 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/doraemon/ci/viewmodels/vm_ci_task_queue.py", line 59, in start_by_avatar
    started_by=User.objects.get(id=ci_task_history.StartedBy)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 14:50:21 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/doraemon/ci/viewmodels/vm_ci_task_queue.py", line 59, in start_by_avatar
    started_by=User.objects.get(id=ci_task_history.StartedBy)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 14:50:26 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/doraemon/ci/viewmodels/vm_ci_task_queue.py", line 59, in start_by_avatar
    started_by=User.objects.get(id=ci_task_history.StartedBy)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 14:50:31 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/doraemon/ci/viewmodels/vm_ci_task_queue.py", line 59, in start_by_avatar
    started_by=User.objects.get(id=ci_task_history.StartedBy)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 14:50:36 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/doraemon/ci/viewmodels/vm_ci_task_queue.py", line 59, in start_by_avatar
    started_by=User.objects.get(id=ci_task_history.StartedBy)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 14:50:41 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/doraemon/ci/viewmodels/vm_ci_task_queue.py", line 59, in start_by_avatar
    started_by=User.objects.get(id=ci_task_history.StartedBy)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 14:50:46 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/doraemon/ci/viewmodels/vm_ci_task_queue.py", line 59, in start_by_avatar
    started_by=User.objects.get(id=ci_task_history.StartedBy)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 14:50:51 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/doraemon/ci/viewmodels/vm_ci_task_queue.py", line 59, in start_by_avatar
    started_by=User.objects.get(id=ci_task_history.StartedBy)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 14:50:56 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/doraemon/ci/viewmodels/vm_ci_task_queue.py", line 59, in start_by_avatar
    started_by=User.objects.get(id=ci_task_history.StartedBy)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 14:51:01 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/doraemon/ci/viewmodels/vm_ci_task_queue.py", line 59, in start_by_avatar
    started_by=User.objects.get(id=ci_task_history.StartedBy)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 14:51:06 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/doraemon/ci/viewmodels/vm_ci_task_queue.py", line 59, in start_by_avatar
    started_by=User.objects.get(id=ci_task_history.StartedBy)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 14:51:11 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/doraemon/ci/viewmodels/vm_ci_task_queue.py", line 59, in start_by_avatar
    started_by=User.objects.get(id=ci_task_history.StartedBy)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 14:51:16 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/doraemon/ci/viewmodels/vm_ci_task_queue.py", line 59, in start_by_avatar
    started_by=User.objects.get(id=ci_task_history.StartedBy)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 14:51:21 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/doraemon/ci/viewmodels/vm_ci_task_queue.py", line 59, in start_by_avatar
    started_by=User.objects.get(id=ci_task_history.StartedBy)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 14:51:26 simplelogger.py[line:28] ERROR User matching query does not exist.
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/doraemon/ci/viewmodels/vm_ci_task_queue.py", line 59, in start_by_avatar
    started_by=User.objects.get(id=ci_task_history.StartedBy)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.
Thu, 01 Nov 2018 14:51:31 simplelogger.py[line:28] ERROR list index out of range
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/ci_model_manager.py", line 168, in get_by_tqid
    result = self.all().filter(TaskQueueID=tq_id)[0]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 307, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
Thu, 01 Nov 2018 14:51:31 simplelogger.py[line:28] ERROR list index out of range
Traceback (most recent call last):
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/doraemon/ci/viewmodels/vm_ci_task_queue.py", line 58, in start_by_avatar
    ci_task_history=CITaskHistory.objects.get_history_by_tq(self.ci_task_queue.id)
  File "/Users/ethan/Documents/OneDrive/github/Teamcat/distribute/0.0.2/build_shell/teamcat/model_managers/ci_model_manager.py", line 187, in get_history_by_tq
    return result[0]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/django/db/models/query.py", line 307, in __getitem__
    return qs._result_cache[0]
IndexError: list index out of range
